source 'https://rubygems.org'
ruby '2.3.5'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-activerecord'

gem 'erubis'
gem 'activesupport', '~>' '4.1.11'
gem 'rake'
gem 'rack', '~>' '1.5.4'
gem 'rack-standards'
gem 'redcarpet', '~>3.1.1'
gem 'dalli'
gem 'builder'
gem 'sprockets', '~>' '2.12.3'
gem 'uglifier'
gem 'closure-compiler'
gem 'coffee-script'
gem 'stylus'
gem 'stylus-source'
gem 'sqlite3', '~>' '1.3.5'
gem 'eco'
gem 'json'
gem 'sinatra-contrib'
gem 'markdown'

group :development do
  gem 'pry'
  gem 'thin'
end
